name: RCPermissions
main: de.raidcraft.permissions.PermissionsPlugin
version: ${project.version}#${build.number}
author: Silthus
website: www.raid-craft.de
depend: [RaidCraft-API, Vault]
softdepend: [RCSkills]
api-version: 1.13